# Site Settings
locale                   : 
title                    : 
subtitle                 : 

url                      : 
baseurl                  : 

# Theme Settings
highlight-skin           : monokai #See http://jwarby.github.io/jekyll-pygments-themes

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
