# theme: jekyll-theme-cayman
# remote_theme: benbalter/retlab


plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap

kramdown:
  input: GFM

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
