# A. Site Settings
locale          :      # Fallback "en-US"
title           :      # Fallback "repository_name" REV
title_separator :      # Fallback " | "
subtitle        : 

url             : 
baseurl         : 

# B. Theme Settings
# Code highlighter 
highlight-skin  :      # Fallback "default" #See http://jwarby.github.io/jekyll-pygments-themes for options

# Google Fonts https://fonts.google.com/
googlefonts:
#  - url : 'https://fonts.googleapis.com/css2?family=Lato&display=swap'
#  - url : 'https://fonts.googleapis.com/css2?family=Lora:wght@500&display=swap'
  

# Theme and colors
chulapa-col: 
  main: 'aquamarine'

chulapa-skin: 
  mode        :     # Fallback "auto", values: auto, custom, ...
  cols        :    
    chulapa-col: # Fallback "crimson"
    body-color: 

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap

# XX. Other settings - no need to modify
# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
