# A. Site Settings
locale          :      # Fallback "en-US"
title           :  Chulapa # Fallback "repository_name" REV
title_separator :      # Fallback " | "
subtitle        :  A Jekyll theme powered by Bootstrap 

url             : 
baseurl         : 

# Site Author
author:
  name: DHH


# B. Navigations

navbar:
  brand:
    title: Chulapa
    url: 
    img: https://i1.wp.com/www.gritosdemadrid.es/wp-content/uploads/2018/05/15x15-Puerta-del-Sol-Cartel-Calle-Azulejo.jpg
  nav:
  - title: Showcase
    url: /bootstrap
  - title: Second Level
    child:
    - title: Liquid examples
      url:  /liquid
    - title: External url
      url: https://www.google.com/
  - title: Another
    child:
    - title: New
      url: /new
    - title: External url
      url: https://www.google.com/
  - title: Github
    url: https://github.com/dieghernan

footer:
  links:
    - label: "RSS"
      icon: "fa-rss"
      url:  https://www.example.com
    - label: "Twitter"
      icon: "fa-twitter"
      # url:
    - label: "Facebook"
      icon: "fa-facebook"
    - label: "GitHub"
      icon: "fa-github"
      # url:
    - label: "Instagram"
      icon: "fa-instagram"
  

# C. Theme Settings
# Code highlighter 
highlight-skin  :      # Fallback "default" #See http://jwarby.github.io/jekyll-pygments-themes for options

# Google Fonts https://fonts.google.com/, add as many as you want
googlefonts:
  - url : 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'

  

# Theme and colors
chufont:
  font-family-sans-serif: Calibri, sans-serif

chulapa-skin: 
  highlight   :  # Fallback "default" #See http://jwarby.github.io/jekyll-pygments-themes for options
  theme       : lux # Optional predefined skins
  autothemer  :   # Bool: Use autotheming
  vars        :    
    chulapa-col:       # Fallback "crimson"
    font-family-sans-serif: #Roboto, sans-serif
    hero-chulapa-bg-color: 
    

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap

# XX. Other settings - no need to modify
# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
